import type { Article } from './types'

const now = Date.now()
const ago = (min: number) => new Date(now - min * 60_000).toISOString()

export const MOCK_ARTICLES: Article[] = [
  {
    id: 'mock-1',
    title: 'Bitcoin doorbreekt €60.000: analisten verwachten verdere stijging richting nieuw all-time high',
    slug: 'bitcoin-doorbreekt-60000-analisten-verwachten-verdere-stijging',
    excerpt: 'De koers van Bitcoin is voor het eerst in maanden boven de €60.000 uitgestegen. Marktexperts zien dit als een sterk signaal en verwachten dat het bullseizoen pas begint.',
    content: '<p>Bitcoin artikel placeholder</p>',
    image_url: 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=1200&q=80',
    image_alt: 'Bitcoin gouden munt',
    source_url: null, source_name: null,
    author_name: 'Acrypto Redactie',
    category: 'bitcoin', tags: ['bitcoin', 'koers', 'analyse'],
    status: 'published', featured: true, view_count: 2841,
    published_at: ago(38), created_at: ago(38), updated_at: ago(38),
  },
  {
    id: 'mock-2',
    title: 'Ethereum Pectra-upgrade live: dit zijn de vijf grootste veranderingen voor gebruikers',
    slug: 'ethereum-pectra-upgrade-live-grootste-veranderingen',
    excerpt: 'De langverwachte Ethereum Pectra-upgrade is succesvol geactiveerd op het mainnet. De update brengt lagere fees en snellere transacties voor miljoenen gebruikers.',
    content: '<p>Ethereum artikel placeholder</p>',
    image_url: 'https://images.unsplash.com/photo-1622630998477-20aa696ecb05?w=800&q=80',
    image_alt: 'Ethereum logo',
    source_url: null, source_name: null,
    author_name: 'Acrypto Redactie',
    category: 'ethereum', tags: ['ethereum', 'upgrade', 'pectra'],
    status: 'published', featured: false, view_count: 1543,
    published_at: ago(105), created_at: ago(105), updated_at: ago(105),
  },
  {
    id: 'mock-3',
    title: 'SEC keurt drie nieuwe Bitcoin ETF-aanvragen goed — institutioneel kapitaal stroomt de markt in',
    slug: 'sec-keurt-drie-nieuwe-bitcoin-etf-aanvragen-goed',
    excerpt: 'De Amerikaanse toezichthouder SEC heeft groen licht gegeven voor drie nieuwe spot Bitcoin ETFs. Analisten verwachten dat dit miljarden aan institutioneel geld aantrekt.',
    content: '<p>SEC ETF artikel placeholder</p>',
    image_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80',
    image_alt: 'Trading schermen',
    source_url: null, source_name: null,
    author_name: 'Acrypto Redactie',
    category: 'regulering', tags: ['bitcoin', 'etf', 'sec', 'institutioneel'],
    status: 'published', featured: false, view_count: 987,
    published_at: ago(190), created_at: ago(190), updated_at: ago(190),
  },
  {
    id: 'mock-4',
    title: 'Solana breekt record: $10 miljard dagelijks handelsvolume voor het eerst in de geschiedenis',
    slug: 'solana-breekt-record-10-miljard-dagelijks-handelsvolume',
    excerpt: 'Solana heeft een historisch record bereikt met meer dan tien miljard dollar aan dagelijks handelsvolume op de keten. De koers van SOL steeg in reactie hierop met meer dan 8 procent.',
    content: '<p>Solana artikel placeholder</p>',
    image_url: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80',
    image_alt: 'Crypto blockchain netwerk',
    source_url: null, source_name: null,
    author_name: 'Acrypto Redactie',
    category: 'altcoins', tags: ['solana', 'volume', 'record'],
    status: 'published', featured: false, view_count: 764,
    published_at: ago(310), created_at: ago(310), updated_at: ago(310),
  },
  {
    id: 'mock-5',
    title: 'DeFi total value locked stijgt naar $150 miljard — Aave en Uniswap leiden de opmars',
    slug: 'defi-total-value-locked-150-miljard-aave-uniswap',
    excerpt: 'Het totaal vergrendelde vermogen in gedecentraliseerde financiën heeft voor het eerst de grens van 150 miljard dollar gepasseerd, aangedreven door sterke groei bij Aave en Uniswap.',
    content: '<p>DeFi artikel placeholder</p>',
    image_url: 'https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=800&q=80',
    image_alt: 'DeFi blockchain',
    source_url: null, source_name: null,
    author_name: 'Acrypto Redactie',
    category: 'defi', tags: ['defi', 'aave', 'uniswap', 'tvl'],
    status: 'published', featured: false, view_count: 521,
    published_at: ago(450), created_at: ago(450), updated_at: ago(450),
  },
  {
    id: 'mock-6',
    title: 'Belastingdienst Nederland: zo geef je jouw crypto correct op in 2025',
    slug: 'belastingdienst-nederland-crypto-opgeven-2025',
    excerpt: 'De Belastingdienst heeft duidelijkheid gegeven over hoe Nederlandse crypto-houders hun bezittingen in 2025 moeten opgeven in box 3. Wat verandert er ten opzichte van vorig jaar?',
    content: '<p>Belasting artikel placeholder</p>',
    image_url: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80',
    image_alt: 'Belastingformulier',
    source_url: null, source_name: null,
    author_name: 'Acrypto Redactie',
    category: 'regulering', tags: ['belasting', 'nederland', 'wetgeving'],
    status: 'published', featured: false, view_count: 3102,
    published_at: ago(620), created_at: ago(620), updated_at: ago(620),
  },
  {
    id: 'mock-7',
    title: 'BlackRock Bitcoin ETF bereikt $20 miljard beheerd vermogen — snelste groei in ETF-geschiedenis',
    slug: 'blackrock-bitcoin-etf-20-miljard-beheerd-vermogen',
    excerpt: 'De Bitcoin ETF van vermogensbeheerder BlackRock heeft de kaap van 20 miljard dollar in beheerd vermogen bereikt. Het is de snelst groeiende ETF die ooit werd gelanceerd.',
    content: '<p>BlackRock ETF artikel placeholder</p>',
    image_url: 'https://images.unsplash.com/photo-1611079829529-fc15b25f72f4?w=800&q=80',
    image_alt: 'Investeringen financiën',
    source_url: null, source_name: null,
    author_name: 'Acrypto Redactie',
    category: 'bitcoin', tags: ['blackrock', 'etf', 'institutioneel'],
    status: 'published', featured: false, view_count: 1890,
    published_at: ago(780), created_at: ago(780), updated_at: ago(780),
  },
  {
    id: 'mock-8',
    title: 'Marktanalyse: altcoin seizoen in aantocht? Fear & Greed index staat op \'Extreme Greed\'',
    slug: 'marktanalyse-altcoin-seizoen-aantocht-fear-greed',
    excerpt: 'De Crypto Fear & Greed index staat op 88 — extreme hebzucht. Historisch gezien is dit een periode waarin altcoins het sterk doen. Maar is voorzichtigheid geboden?',
    content: '<p>Marktanalyse artikel placeholder</p>',
    image_url: 'https://images.unsplash.com/photo-1535320903710-d993d3d77d29?w=800&q=80',
    image_alt: 'Koersgrafiek analyse',
    source_url: null, source_name: null,
    author_name: 'Acrypto Redactie',
    category: 'marktanalyse', tags: ['altcoins', 'analyse', 'fear-greed'],
    status: 'published', featured: false, view_count: 1234,
    published_at: ago(960), created_at: ago(960), updated_at: ago(960),
  },
]
